export {
  ALMACEN_DEFAULT,
  ALMACEN_TIPOS,
  ARMARIOS,
  buildCodigo,
  buildContenedorId,
  buildDbId,
  codigoLookupVariants,
  getAlmacenNombre,
  getArmarioNombre,
  listAlmacenes,
  listArmarios,
  mapUbicacionFields,
  normalizeAlmacen,
  normalizeArmario,
  normalizeContenedor,
  normalizeEstante,
  parseCodigo,
} from './ubicacionUtils.js';
