export {
  ALMACEN_DEFAULT,
  ALMACEN_TIPOS,
  ARMARIO_TIPOS,
  buildCodigo,
  buildContenedorId,
  buildDbId,
  codigoLookupVariants,
  contenedorMatchesParsed,
  getAlmacenNombre,
  getArmarioNombre,
  getArmariosMapForAlmacen,
  getArmariosMapSync,
  listAlmacenes,
  listArmarios,
  listArmariosPorAlmacen,
  mapUbicacionFields,
  normalizeAlmacen,
  normalizeArmario,
  normalizeContenedor,
  normalizeEstante,
  parseCodigo,
} from './ubicacionUtils.js';
